version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=networthtracker_dev
      - POSTGRES_USER=networthtracker
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Django Application (Development)
  web:
    build: .
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - media_files:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.docker_settings
      - DATABASE_URL=postgresql://networthtracker:dev_password@db:5432/networthtracker_dev
      - SECRET_KEY=dev-secret-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Nginx (Development - optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/staticfiles:ro
      - media_files:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_files:
  media_files: 