# Generated by Django 4.2.23 on 2025-08-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('classification', models.CharField(choices=[('pretax', 'Pre-Tax'), ('posttax', 'Post-Tax'), ('roth', 'Roth'), ('traditional', 'Traditional IRA'), ('401k', '401(k)'), ('529', '529 Plan'), ('hsa', 'HSA'), ('fsa', 'FSA'), ('taxable', 'Taxable'), ('debts', 'Debts'), ('other', 'Other')], default='other', max_length=20)),
                ('asset_type', models.CharField(choices=[('cash', 'Cash & Cash Equivalents'), ('crypto', 'Cryptocurrency'), ('property', 'Real Estate'), ('vehicles', 'Vehicles'), ('jewelry', 'Jewelry & Watches'), ('art', 'Art & Collectibles'), ('electronics', 'Electronics'), ('furniture', 'Furniture & Appliances'), ('clothing', 'Clothing & Accessories'), ('books', 'Books & Media'), ('sports', 'Sports Equipment'), ('tools', 'Tools & Equipment'), ('other', 'Other Assets')], default='cash', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=20)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('food', 'Food & Dining'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('travel', 'Travel'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('year', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.account')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('account', 'month', 'year')},
            },
        ),
    ]
