# Generated by Django 4.2.23 on 2025-07-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.CharField(choices=[('pretax', 'Pre-Tax'), ('posttax', 'Post-Tax'), ('roth', 'Roth'), ('traditional', 'Traditional IRA'), ('401k', '401(k)'), ('hsa', 'HSA'), ('fsa', 'FSA'), ('taxable', 'Taxable'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
