# Generated by Django 4.2.23 on 2025-07-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_account_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='asset_type',
            field=models.CharField(choices=[('cash', 'Cash & Cash Equivalents'), ('property', 'Real Estate'), ('vehicles', 'Vehicles'), ('jewelry', 'Jewelry & Watches'), ('art', 'Art & Collectibles'), ('electronics', 'Electronics'), ('furniture', 'Furniture & Appliances'), ('clothing', 'Clothing & Accessories'), ('books', 'Books & Media'), ('sports', 'Sports Equipment'), ('tools', 'Tools & Equipment'), ('other', 'Other Assets')], default='cash', max_length=20),
        ),
    ]
