# Generated by Django 4.2.23 on 2025-07-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_account_asset_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
