# Generated by Django 4.2.23 on 2025-07-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_account_balance_accountentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='classification',
            field=models.CharField(choices=[('pretax', 'Pre-Tax'), ('posttax', 'Post-Tax'), ('roth', 'Roth'), ('traditional', 'Traditional IRA'), ('401k', '401(k)'), ('hsa', 'HSA'), ('fsa', 'FSA'), ('taxable', 'Taxable'), ('debts', 'Debts'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
